### ISSUE TITLE
powerai cudatoolkit 10.1 doesn't allow profiling 

### ISSUE THREAD

**Issue by Clyde-fare** [IBM/powerai#35]
This is an issue affecting CUDA 10.1 defaulting to requiring administrator access to use the nvprof tool.[1,2]. Is it possible package a version of cudatool kit added to powerAI that will allow profiling?

Many thanks.

[1] https://developer.nvidia.com/nvidia-development-tools-solutions-err-nvgpuctrperm-NsightCompute
[2] https://devtalk.nvidia.com/default/topic/1049421/visual-profiler-and-nvprof/nvprof-warning-the-user-does-not-have-permission-to-profile-on-the-target-device-/

**Comment by smatzek** [comment]
As you probably know from the links you posted, this was an intentional change by NVIDIA to address a security issue that allowed non-admin users to see data processed by the GPU by other non-admin users. https://nvidia.custhelp.com/app/answers/detail/a_id/4738

This NVIDIA document contains instructions on how to re-enable profiling for non-admin users, but in doing so you do expose the system to the security vulnerability that was fixed: https://developer.nvidia.com/nvidia-development-tools-solutions-ERR_NVGPUCTRPERM-permission-issue-performance-counters

**Comment by Clyde-fare** [comment]
Hi thanks, for looking into this. I don't really see any way to re-enable profiling for a non-admin as both sudo and CAP_SYS_ADMIN require admin privledges but I guess I need to take this up with my sysadmin. Thanks again.
